title: Mackenzie Arts
description: >-
  WLMAC Arts Council events and information.
baseurl: "" # TODO: Remove when migrating to domain
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# copyright: "&copy; 2020 Mackenzie Arts Council."

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Display posts / events with a future date
future: true

nav_links:
  Events: /events/
  Calendar: /calendar/
  Announcements: /announcements/
  Councils: /about/
  Departments:
    Music: /departments/music/
    Drama: /departments/drama/
    Dance: /departments/dance/
    Visual & Digital Arts: /departments/visual-arts/
    Staff: /staff/

collections:
  departments:
    output: true
    permalink: /departments/:name/
  events:
    output: true
    permalink: /events/:slug/

defaults:
  - scope:
      path: "_departments"
    values:
      layout: "department"
      subheading: "Department Page"
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "_events"
    values:
      layout: "event"
      image: "/assets/img/logo.svg"

  # Prevent event thumbnails from appearing in galleries
  - scope:
      path: "assets/img/events/thumbnails"
    values:
      gallery_ignore: true

  # For display pages
  - scope:
      path: "assets/img/dance"
    values:
      tag: "dance"
  - scope:
      path: "assets/img/drama"
    values:
      tag: "drama"
  - scope:
      path: "assets/img/music"
    values:
      tag: "music"
  - scope:
      path: "assets/img/visual-arts"
    values:
      tag: "visual"
